# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6bce3d10b6d93c0a37b05e0de43f090d1617ff5608c08b192d1e3f9d1c1892e49d8ef9a644a78c603c86663128d772e934866f9b9fe4724eb6d83b4ff2b5432

test:
  secret_key_base: ea2943fce73f7f6935efdccaf617903de0ee759bfb54a5401d48f9217acf718d9d6f46807fb8afe1511a661d4ebd47c4b0fa4ba01c3d8965fa50cd94790c809b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
